### ISSUE TITLE
用zookeeper监控kafka情况

### ISSUE THREAD

**Issue by suesunss** [tqlihuiqi/kzmonitor#5]
你好，我目前在做关于kafka监控的项目，网上有很多例子，比如kafka manager, kafka monitor等。对你这个项目很感兴趣，我想问一下，如果不用kafka 的python client，可以纯粹用kazoo来监控kafka吗？尤其是producer端的流量信息（也包括你在代码里用kafka client做的逻辑），但我想只用kazoo，这样可以实现吗？

**Comment by tqlihuiqi** [comment]
你好，这个项目最初的目的就是要监控多版本的Kafka的延迟，Kafka从0.8.2开始提供了__consumer_offsets的topic存储offsets，因此只使用kazoo是不行的。

**Comment by suesunss** [comment]
感谢你的回复，关于kafka的监控报警整个系统，请问你有什么方案建议吗？哪些方案比较好？你这个方案不错，但如果应用到更大规模（甚至企业级）呢？

**Comment by suesunss** [comment]
我看了很多方案，比如基于kafka manager来改，基于kafka-monitor，利用JMX来写，通过client来写等等，也有很多第三方的方案，比如小米的open-falcon提供了一个不错的framework，但要自己去编写agent脚本，你在这方面比较有经验，请问你有什么建议吗？

**Comment by tqlihuiqi** [comment]
主要还是看你现有环境用什么做监控，一般使用Falcon/Zabbix的话如果不想做二次开发都会直接用agent去获取要监控的数据然后进行上报。

**Comment by suesunss** [comment]
fixed. Thanks.目前基于kafka-python和open-falcon已经能满足需求
